#spring.application.name=backen
server.port=8080

# 프론트 주소
#app.cors.allowed-origins=http://localhost:3000,http://192.168.10.25:3000
app.cors.allowed-origins=http://localhost:3000

# Oracld db 연결 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=ARCADEV
spring.datasource.password=ARCADEV1234
